// Code generated by muster. DO NOT EDIT.
package main

func (f Foo) MustBlahWithRecv(s int, a Foo) int {
	val, err := f.BlahWithRecv(s, a)
	if err != nil {
		panic(err)
	}
	return val
}
func MustBlah(s int, a Foo) int {
	val, err := Blah(s, a)
	if err != nil {
		panic(err)
	}
	return val
}
func MustBlah3(s int, a Foo) Foo {
	val, err := Blah3(s, a)
	if err != nil {
		panic(err)
	}
	return val
}

func MustWithTemplate(tmplstr string, data interface{}, funcs ...interface{}) string {
	val, err := WithTemplate(tmplstr, data, funcs)
	if err != nil {
		panic(err)
	}
	return val
}
