// Code generated by muster. DO NOT EDIT.
// see https://github.com/joshcarp/muster for more details.
package main

import (
	foobar "github.com/googleapis/gax-go/v2"
)

// MustBlahWithRecv calls BlahWithRecv and panics if err is not nil.
func (f Foo) MustBlahWithRecv(s int, a *Foo) *int {
	val, err := f.BlahWithRecv(s, a)
	if err != nil {
		panic(err)
	}
	return val
}

// MustBlah calls Blah and panics if err is not nil.
func MustBlah(s int, a Foo) int {
	val, err := Blah(s, a)
	if err != nil {
		panic(err)
	}
	return val
}

// MustBlah3 calls Blah3 and panics if err is not nil.
func MustBlah3(s int, a Foo) Foo {
	val, err := Blah3(s, a)
	if err != nil {
		panic(err)
	}
	return val
}

// MustMustSpannerBlah3 calls MustSpannerBlah3 and panics if err is not nil.
func MustMustSpannerBlah3(s foobar.Backoff, a Foo) Foo {
	val, err := MustSpannerBlah3(s, a)
	if err != nil {
		panic(err)
	}
	return val
}

// MustWithTemplate calls WithTemplate and panics if err is not nil.
func MustWithTemplate(tmplstr string, data interface{}, funcs ...interface{}) string {
	val, err := WithTemplate(tmplstr, data, funcs)
	if err != nil {
		panic(err)
	}
	return val
}
