// Code generated by muster. DO NOT EDIT.
package main

//
func (recv Foo) MustBlah(param0 int, param1 Foo) int {
	val, err := recv.Blah(param0, param1)
	if err != nil {
		panic(err)
	}
	return val
}

func MustBlah(param0 int, param1 Foo) int {
	val, err := Blah(param0, param1)
	if err != nil {
		panic(err)
	}
	return val
}
