package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"io/ioutil"
	"log"
	"os"
	"strings"
	"text/template"

	"golang.org/x/tools/imports"

	"github.com/iancoleman/strcase"
	"golang.org/x/tools/go/packages"
)

var (
	output = flag.String("output", "", "output file name; default srcdir/<file>_must.go")
)

// Usage is a replacement usage function for the flags package.
func Usage() {
	fmt.Fprintf(os.Stderr, "Usage of stringer:\n")
	fmt.Fprintf(os.Stderr, "\tstringer [flags] -type T [directory]\n")
	fmt.Fprintf(os.Stderr, "\tstringer [flags] -type T files... # Must be a single package\n")
	fmt.Fprintf(os.Stderr, "For more information, see:\n")
	fmt.Fprintf(os.Stderr, "\thttps://pkg.go.dev/golang.org/x/tools/cmd/stringer\n")
	fmt.Fprintf(os.Stderr, "Flags:\n")
	flag.PrintDefaults()
}

func main() {
	log.SetFlags(0)
	log.SetPrefix("stringer: ")
	flag.Usage = Usage
	flag.Parse()
	var tags []string

	// We accept either one directory or a list of files. Which do we have?
	args := flag.Args()
	if len(args) == 0 {
		// Default: process whole package in current directory.
		args = []string{"."}
	}

	// Parse the package once.
	var g Generator

	g.parsePackage(args, tags)

	// Run generate for each type.
	g.generate()

}

// Generator holds the state of the analysis. Primarily used to buffer
// the output for format.Source.
type Generator struct {
	Pkg         *Package // Package we are scanning.
	Fset        *token.FileSet
	trimPrefix  string
	lineComment bool
}

// File holds a single parsed file and associated data.
type File struct {
	buf     bytes.Buffer // Accumulated output.
	pkg     *Package     // Package to which this file belongs.
	file    *ast.File    // Parsed AST.
	fset    *token.FileSet
	Imports []string
}

type Package struct {
	Name  string
	Files []*File
}

// parsePackage analyzes the single package constructed from the patterns and tags.
// parsePackage exits if there is an error.
func (g *Generator) parsePackage(patterns []string, tags []string) {
	cfg := &packages.Config{
		Mode: packages.LoadSyntax,
		Tests:      false,
		BuildFlags: []string{fmt.Sprintf("-tags=%s", strings.Join(tags, " "))},
	}
	pkgs, err := packages.Load(cfg, patterns...)
	if err != nil {
		log.Fatal(err)
	}
	if len(pkgs) != 1 {
		log.Fatalf("error: %d packages found", len(pkgs))
	}
	g.addPackage(pkgs[0])
}

// addPackage adds a type checked Package and its syntax files to the generator.
func (g *Generator) addPackage(pkg *packages.Package) {
	g.Pkg = &Package{
		Name:  pkg.Name,
		Files: make([]*File, len(pkg.Syntax)),
	}
	g.Fset = pkg.Fset
	for i, file := range pkg.Syntax {
		g.Pkg.Files[i] = &File{
			file: file,
			pkg:  g.Pkg,
			fset: pkg.Fset,
		}
		for _, impt := range file.Imports {
			g.Pkg.Files[i].Imports = append(g.Pkg.Files[i].Imports, NodeAsString(pkg.Fset, impt))
		}
	}
}

// generate produces the String method for the named type.
func (g *Generator) generate() {
	var out bytes.Buffer
	tmpl := `// Code generated by muster. DO NOT EDIT.
// see https://github.com/joshcarp/muster for more details.
package {{.Pkg.Name}}
import (
{{range $i, $e := .Pkg.Files}}{{range $j, $import := .Imports}}
{{$import}}{{end}}{{end}})
{{range $i, $e := .Pkg.Files}}
{{$e.Generate}}
{{end}}
`
	musttmpl := template.Must(template.New("").Parse(tmpl))
	err := musttmpl.Execute(&out, g)
	if err != nil {
		log.Println(err)
	}

	ioutil.WriteFile(g.Pkg.Name+"_must.go", []byte(importCode(out.String())), 0644)
}

// importCode returns the gofmt-ed contents of the Generator's buffer.
func importCode(buf string) string {
	src, err := imports.Process("", []byte(buf), nil)
	if err != nil {
		// Should never happen, but can arise when developing this code.
		// The user can compile the output to see the error.
		log.Printf("warning: internal error: invalid Go generated: %s", err)
		log.Printf("warning: compile the package to analyze the error")
		return buf
	}
	return string(src)
}

func formatCode(buf string) string {
	src, err := format.Source([]byte(buf))
	if err != nil {
		// Should never happen, but can arise when developing this code.
		// The user can compile the output to see the error.
		log.Printf("warning: internal error: invalid Go generated: %s", err)
		log.Printf("warning: compile the package to analyze the error")
		return buf
	}
	return string(src)
}


func (f *File) Generate() string {
	ast.Inspect(f.file, f.genDecl)
	return f.buf.String()
}

// genDecl processes one declaration clause.
func (f *File) genDecl(node ast.Node) bool {
	decl, ok := node.(*ast.FuncDecl)
	if !ok {
		return true
	}
	if decl.Type == nil {
		return true
	}
	if decl.Type.Results == nil {
		return true
	}
	if len(decl.Type.Results.List) != 2 {
		return true
	}
	if NodeAsString(f.fset, decl.Type.Results.List[1].Type) != "error" {
		return true
	}
	call := FromDecl(decl, f.fset)
	must := call
	var err error
	must.Body, err = WithTemplate(
		`val, err := {{if ne .Recv.Name ""}}{{.Recv.Name}}.{{end}}{{.Name}}({{ range $i, $e := .Params }}{{$e.Name}}, {{end}})
	if err != nil {
		panic(err)
	}
	return val`, must)
	if err != nil {
		log.Printf("error printing function %s", must.Name)
	}
	switch must.IsExported() {
	case true:
		must.Name = "Must" + must.Name
	case false:
		must.Name = "must" + strcase.ToCamel(must.Name)
	}
	must.Returns = must.Returns[:len(must.Returns)-1]
	must.Comment = fmt.Sprintf("// %s calls %s and panics if err is not nil.", must.Name, call.Name)
	f.buf.Write([]byte(must.String()))
	return false
}
